# Generated by Django 3.2.7 on 2021-12-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advetiesments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_type', models.CharField(choices=[('Com', 'Computer'), ('Mob', 'Mobile'), ('Grs', 'Grocessory'), ('Tex', 'Textile'), ('Fod', 'Food'), ('Oth', 'Other')], default='Non', max_length=3)),
                ('image', models.ImageField(blank=True, upload_to='advertiesments/')),
            ],
        ),
    ]
