# Generated by Django 3.2.7 on 2021-10-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211005_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='search_item_name',
            field=models.IntegerField(),
        ),
    ]
